[package]
name = "ckb-sdk"
version = "1.1.0"
authors = ["Linfeng Qian <thewawar@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "Rust SDK for CKB"
homepage = "https://github.com/nervosnetwork/ckb-sdk"
repository = "https://github.com/nervosnetwork/ckb-sdk"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
bech32 = "0.8.1"
log = "0.4.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
secp256k1 = { version = "0.20", features = ["recovery"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio = { version = "1" }
bytes = "1"
futures = "0.3"
jsonrpc-core = "18"
parking_lot = "0.12"
lru = "0.7.1"

ckb-types = "=0.104.0"
ckb-dao-utils = "=0.104.0"
ckb-traits = "=0.104.0"
ckb-jsonrpc-types = "=0.104.0"
ckb-hash = "=0.104.0"
ckb-resource = "=0.104.0"
ckb-crypto = { version = "=0.104.0", features = ["secp"] }

molecule = "0.7.2"

# for feature test
rand = { version = "0.7.3", optional = true }
ckb-mock-tx-types = { version = "0.4.0", optional = true }
ckb-chain-spec = { version = "=0.104.0", optional = true }
ckb-script = { version = "=0.104.0", optional = true }

[features]
default = []
test = []

[dev-dependencies]
clap = { version = "3.1.9", features = ["derive"] }
httpmock = "0.6"
async-global-executor = "=2.0.4"
hex = "0.4"
